### ISSUE TITLE
Installing this module set

### ISSUE THREAD

**Issue by danbuntu** [MSOpenTech/moodle-local_o365#1]
Excuse my ignorance but how do I actually install this module set?

When I upload them them all to my moodle dev server I get the notice that there are new modules to install but they fail due dependencies - despite being dependant on each other and all being present. I'm not aware of any method that allows me to force the install with missing dependencies.

I'm concerned that if there is a correct order to install these then went I git pull to my live server from my dev then I'm going to face the same problem.

**Comment by jamesmcq** [comment]
@danbuntu 

There's no correct order to install them - they can all be installed at once. You *might* be running into issues with the version number though - you should be sure to install all the current versions for the same Moodle version. Plugins for Moodle 2.7 start with v27, Moodle 2.8 start with v28, etc.

Can you double check you're using the current version of each plugin, and the correct versions for the Moodle version you're running? If that doesn't help, can you post the specific messages you're seeing? (i.e. exactly what Moodle is reporting is missing), as well as a list of the plugins you have and their respective versions.

Thanks!

**Comment by danbuntu** [comment]
I've now got the module set installed and I can login via office 365

My next question though is is there any support for single sign on?

For example we use Collabco Myday which in turn uses Iamcloud. So when a student opens a browser it opens their student portal and sso's them in based on there windows login.

If I then go to my text moodle it doesn't automatically sign them in. But if they click on the login with office 365 button then it goes breifly to login.microsfotonline.com and then back to moodle and logns them - This is using I assume the federated login set in when they logged into the portal.

Is there a way to have this log straight in without having to click the button.
I hope I have explained this properly.

**Comment by jamesmcq** [comment]
The best thing to do is direct your users to [your moodle url]/auth/oidc/ as this will log them in to Moodle as long as they are logged in to Office 365. If they're not logged in to Office365 it will direct them to log in on the Office site, then redirect them back to Moodle logged in. This is the URL they're sent to when they click the login with Office365 button.

**Comment by danbuntu** [comment]
Thats good to know thankyou.

Can I request that Single sign in from the windows desktop goes in as a feature request somewhere please.

**Comment by jamesmcq** [comment]
I've made a note of it, thanks!
